"""
Contains all mappings that are needed
"""

# Dict key is 'CLEAN key' and dict value is 'SDK key'
MAPPING_CLEAN_TO_SDK = {
    "author_email": None,
    "creator_user_id": None,
    "dataQuality": "Informationen oder Risiken, die bei der Nutzung zu beachten sind", 
    "dataType": None,
    "dateFirstPublished": "Erst-Veröffentlichungsdatum OGD",
    "dateLastUpdated": "Aktualisierungsdatum OGD",
    "id": None,
    "isopen": None,
    "legalInformation": "Rechtsgrundlagen", # derivedFrom (label)
    "license_id": "Lizenz", 
    "license_title": None,
    "license_url": None,
    "maintainer": None, # "OGD_maintainer",
    "maintainer_email": None, # "OGD_maintainerEmail",
    "metadata_created": None,
    "metadata_modified": None,
    "name": "Package Name", 
    "notes": "Beschreibung",
    "num_resources": None,
    "num_tags": None,
    "organization": None,
    "owner_org": None,
    "private": None,
    "spatialRelationship": "Geographisches Gebiet",
    "sszBemerkungen": "Weitere Bemerkungen zur Nutzung", 
    "sszFields": None,
    "state": None,
    "temporalStart": "Zeitraum - von",
    "temporalEnd": "Zeitraum - bis",
    "title": "Name",
    "type": None,
    "updateInterval": "Aktualisierungszyklus",
    # "url": "DIST-CP-OGDLIF",
    "datenlieferant": "Datenlieferant", # fuzzy matching
    "version": None,
    "extras": None,
    "groups": "OGD-Kategorie",
    "resources": None,
    "tags": "Schlüsselwörter",
    "relationships_as_subject": None,
    "relationships_as_object": None,
    "attributes": "attributes",
    "author_dept_gs":"author_dept_gs", # not actually a field in SDK > for matching grobstruktur
    "author_da_gs":"author_da_gs", # not actually a field in SDK > for matching grobstruktur
    "ogd_dataset_url": "URL",
    "attr_spoken": "Bezeichnung", # "Fachlicher Attributname",
    "attr_descr": "Beschreibung",
    "attr_tech": "Technischer Feldname",
    "dist_type": "Distributionstyp", # for sdk excel sheet Distributionen
    "dist_of": "Distribution von", # for sdk excel sheet Distributionen
    "dist_name": "Bezeichnung", # for sdk excel sheet Distributionen
    "dist_format": "Format", # for sdk excel sheet Distributionen
}

# keep only entries where value is not None
MAPPING_CLEAN_TO_SDK = {key: value for key, value in MAPPING_CLEAN_TO_SDK.items() if value is not None}

# mappings for readable Codes in SDK-Excel-Import
SDK_EXCEL_UPDATE_INTERVALL = {
    "taeglich": "täglich",
    "   ": "   ",
    "alle 4 Jahre": "alle 4 Jahre",
    "Echtzeit": "Echtzeit",
    "halbjaehrlich": "halbjährlich",
    "jaehrlich": "jährlich",
    "keines": "keines",
    "laufend": "laufend",
    "monatlich": "monatlich",
    "quartalsweise": "quartalsweise",
    "sporadisch oder unregelmaessig": "sporadisch oder unregelmäßig",
    "stuendlich": "stuendlich",
    "vierzehntaeglich": "vierzehntäglich",
    "woechentlich": "wöchentlich",
    "laufende Nachfuehrung": "laufende Nachführung",
    "keine Nachfuehrung": "keine Nachführung",
}

SDK_EXCEL_LICENCE = {
    "cc-zero": "CC-Zero (CC0)", 
    "cc-by": "CC-BY", 
    "cc-by-sa": "CC-BY-SA", 
}

SDK_EXCEL_DATASET_COLNAMES = [
    'Name',
    'Subset von',
    'Kurzbeschreibung',
    'Beschreibung',
    'Synonyme',
    'Schlüsselwörter',
    'Sammlung',
    'Favorit',
    'Gesperrt',
    'Schreibgeschützt',
    'Status',
    'Identifikation',
    'Erstellt von',
    'Erstellt am',
    'Aktualisierungszyklus',
    'Geographisches Gebiet',
    'Zeitraum - von',
    'Zeitraum - bis',
    'Zweck der Datenbearbeitung',
    'OGD-Massnahmen-Prüfung - Status (automatisch)',
    'Links zu weiterführenden Informationen',
    'Zugangsstufe (automatisch)',
    'OGD-Datensatz Beurteilung (automatisch)',
    'Weitere Bemerkungen zur Nutzung',
    'Zugangsstufe - Freigabe durch - Name (automatisch)',
    'OGD-Datensatz Beurteilung - Bemerkung (automatisch)',
    'Zugangsstufe - Freigabe Datum (automatisch)',
    'OGD-Datensatz - Veröffentlichung - Priorisierung und Art',
    'Anwendbares Datenschutzrecht',
    'Personendaten - Personendaten enthalten? (automatisch)',
    'Präzisierung zum Aktualisierungszyklus',
    'OGD-Datensatz Beurteilung - Freigabe durch - Name (automatisch)',
    'Personendaten - Ausnahmeregelung Veröffentlichung - Begründung und/oder Rechtsnorm (automatisch)',
    'OGD-Datensatz Beurteilung - Freigabe - Datum (automatisch)',
    'Informationen oder Risiken, die bei der Nutzung zu beachten sind',
    'Regelung für organisationseinheitsübergreifende Nutzung - Begründung und/oder Rechtsnorm (automatisch)',
    'OGD-Datensatz - Veröffentlichung - Status (automatisch)',
    # 'author_dept_gs',
    # 'author_da_gs',
]

SDK_EXCEL_ATTRIBUTES_COLNAMES = [
    'Bestandteil von',
    'Bezeichnung',
    'Besteht aus',
    'Nr',
    'Kennzeichnung',
    'Name',
    'Titel',
    'Beschreibung',
    'Synonyme',
    'Schlüsselwörter',
    'Favorit',
    'Gesperrt',
    'Schreibgeschützt',
    'Status',
    'Erstellt von',
    'Erstellt am',
    'Technischer Feldname',
    # 'author_dept_gs',
    # 'author_da_gs',
]

SDK_EXCEL_DISTRIBUTIONS_COLNAMES = [
    'Bezeichnung',
    'Distribution von',
    'Nr',
    'Distributionstyp',
    'Titel',
    'Beschreibung',
    'Synonyme',
    'Schlüsselwörter',
    'Favorit',
    'Gesperrt',
    'Schreibgeschützt',
    'Status',
    'Identifikation',
    'Erstellt von',
    'Erstellt am',
    'URL',
    'Format',
    'Größe',
    'Job-ID',
    'Job-Laufnummer',
    'Output-ID',
    'SASA-Job-Output-ID',
    'Titel 1',
    'WAI-Text für Grafik',
    'Titel 2',
    'Dateiname Erläuterungen',
    'Erläuterungen',
    'Bildunterschrift Grafik',
    'Quartierspiegel Mastertabelle',
    'Manuelle Korrekturen',
    'Reihenfolge',
    'Bildunterschrift anzeigen',
    'HDB_SASA_Filter',
    'OGD-Kategorie',
    'URL-Modules-Server',
    'Modules-Server Ablage',
    'Lizenz',
    'Datenlieferant',
    'Package Name',
    'Erst-Veröffentlichungsdatum OGD', #'Go-Live - Erst-Veröffentlichungsdatum OGD',
    'Aktualisierungsdatum OGD',
    'Quartierkarte',
    # 'author_dept_gs',
    # 'author_da_gs',
]

# the distributions df is based on the dataset df
# some column names exist in both, but we want the info only in one of them
# here's the list of columns that get dropped in the distributions df, 
# because non existent cols will be added empty
SDK_EXCEL_DISTRIBUTIONS_EMPY_COLS = [
    "Beschreibung",
    "Schlüsselwörter",
]
